### ISSUE TITLE
Avoid Bleeding Text

### ISSUE THREAD

**Issue by codeviking** [aria42/pdf-structure#10]
Occasionally when we trim to a panel we see stuff like this:

![image](https://cloud.githubusercontent.com/assets/801451/9746998/e9e686f0-562f-11e5-96c3-a1b41ebfc111.png)

Notice the text bleeding in from the top.

Is it possible to refine this a bit so we render cleanly?

**Comment by aria42** [comment]
What's the PDF for this?

**Comment by codeviking** [comment]
I see this on quite a few, but here's a good example:

http://beta.s2.allenai.org/paper/498bb0efad6ec15dd09d941fb309aa18d6df9f5f/read/page/0/panel/1

**Comment by aria42** [comment]
@codeviking is this resolved with #14 ?

**Comment by codeviking** [comment]
Yup, we're good.
