### ISSUE TITLE
Error when reading PDF

### ISSUE THREAD

**Issue by codeviking** [aria42/pdf-structure#15]
This paper:

http://development.s2.allenai.org/paper/78e77bebc95cf392a12ae7b33df256df99b3444c/read/page/0/panel/0

Fails with this error:

![image](https://cloud.githubusercontent.com/assets/801451/9966439/ced1adb2-5df1-11e5-9842-afdeff391fbd.png)

**Comment by aria42** [comment]
Will fix tonight. In general will go to one column view if we crash on something

Sent from Outlook

On Fri, Sep 18, 2015 at 10:41 AM -0700, "Sam Skjonsberg" notifications@github.com wrote:

This paper:

http://development.s2.allenai.org/paper/78e77bebc95cf392a12ae7b33df256df99b3444c/read/page/0/panel/0

Fails with this error:
